### ISSUE TITLE
Tokens and Redis Session

### ISSUE THREAD

**Issue by cloudcompute** [tienduy-nguyen/nestjs-graphql-prisma#146]
Hello

It is not easy to understand the theory/logic behind different types of Tokens that you implemented in the auth-service and auth-resolver. Could you pl. write the entire flow of this functionality so that a novice can understand it.

You are saving current-hash-token in the db while 2 others tokens in Redis. I believe we should not store the JWT tokens on server-side.. if we do so, then the server does not remain stateless. 

Kindly read these two articles
http://cryto.net/~joepie91/blog/2016/06/19/stop-using-jwt-for-sessions-part-2-why-your-solution-doesnt-work/

Thanks

**Comment by tduyng** [comment]
Thanks for your suggestion: " I believe we should not store the JWT tokens on server-side". I just search and read some articles about it. I agree with you. JWT token with session has a lot of issues with security, scalability, and stateless problem...

From now, I will not use session for JWT anymore, for overall next app, I think I will use other ways for auth: 
 - Traditional way: "Token  based authentication - Bearer token".
 - Redis way: using redis db to storage data
 - JWT + Auth0

For this project, I will take time to remove JWT implemention and use full redis for authentication. 
Why redis? Beacause I have intention to implement the caching with it.

-----
And for your question: Why I have 2 layers for authentication: jwt + redis? It just because I want have somthing to delete the validation of jwt token after verified.

For e.g: After registration or after send reset-password, 
1. an token will be generate and stored in Redis db and stored in session
2. an link with that  token will be  send to user email
3. user click that link to validate the registration or reset password
4. after validated successfully, I don't want that token valid anymore so I used redis to delete it before checking the validity of token. If that token not exists in redis db, that's mean token is not valid. --> Here is the reason for "different types of tokens".

I know that is not good idea, but I tried to profit advantage of redis.
--> Like I said above, I will remove jwt and using full redis for auth to avoid the security issue.

**Comment by cloudcompute** [comment]
Thx for your reply.  Storing sessions in redis is the best and using the session identifier is a proven method.

Auth0 is very very expensive. Instead use open source keycloak for authentication and authorization. This one is quite popular. 
https://github.com/keycloak/keycloak

It has nodejs-adapter and several other repositories. You may find them useful.

**Comment by tduyng** [comment]
Oh, thanks so much for your advice. I will try it as soon as possible.
